env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install: true
language: java
jdk:
  - oraclejdk8
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  - npm config set cache $HOME/.npm-cache --global 
  - npm config set prefix $HOME/.npm-prefix --global
  - bash metron/push_npm_cache.sh
script:
  - |
    time mvn -q -T 2C -DskipTests install 
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/metron
  - bash metron/pop_npm_cache.sh

cache:
  directories:
  - $HOME/.npm-cache
  - $HOME/.npm-prefix
  - $HOME/.npm-local/node_modules
  - $HOME/.m2
